title: Carlos Hernandez
description: Director of Software Engineering | Co-Founder | Platform Engineering Leader | Distributed Systems, Omnichannel Platforms & Cloud Modernization
url: "https://carlos-technogi.github.io"
baseurl: ""

theme: jekyll-theme-slate
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  # - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Carlos Hernandez
  email: carlos@braian.ai

logo: /assets/profile.png
# show_downloads: false
